#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/jp_ruby"
require "optparse"

options = {}
parser = OptionParser.new do |opts|
  opts.banner = "使い方: jp-ruby [オプション] <ファイル.jrb>"
  opts.version = JpRuby::VERSION

  opts.on("--dump", "変換されたRubyコードを表示する") do
    options[:dump] = true
  end

  opts.on("-e CODE", "コマンドラインからjp-rubyコードを実行する") do |code|
    options[:eval] = code
  end

  opts.on("--config FILE", "カスタムキーワード設定ファイルを指定する") do |file|
    options[:config] = file
  end

  opts.on("-v", "--version", "バージョンを表示する") do
    puts "jp-ruby #{JpRuby::VERSION}"
    exit
  end

  opts.on("-h", "--help", "ヘルプを表示する") do
    puts opts
    exit
  end
end

parser.parse!

if options[:eval]
  config_path = JpRuby::Config.discover(explicit_path: options[:config])
  config = JpRuby::Config.new(config_path)

  keyword_map = config.build_keyword_map
  class_declaration_keywords = config.build_class_declaration_keywords(keyword_map)

  transpiler = JpRuby::Transpiler.new(options[:eval], filename: "-e",
                                      keyword_map: keyword_map,
                                      class_declaration_keywords: class_declaration_keywords)
  ruby_code = transpiler.transpile

  JpRuby::Runtime.load!(config.build_runtime_map)

  if options[:dump]
    puts ruby_code
  else
    eval(ruby_code, TOPLEVEL_BINDING, "-e", 1) # rubocop:disable Security/Eval
  end
elsif ARGV.empty?
  puts parser
  exit 1
else
  filename = ARGV[0]
  unless File.exist?(filename)
    $stderr.puts "エラー: ファイルが見つかりません: #{filename}"
    exit 1
  end
  JpRuby::Runner.new(filename, options).run
end
